name: CI/CD for AWS Lambda Layer

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run lint and Unit test.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM Packages
        run: npm install

      - name: Check JS syntax
        run: npm run lint

      - name: Run unit tests
        run: npm test

  lambda:
    name: Create Release for AWS Lambda
    needs: [ test ]
    if: contains(github.ref, 'tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create Package for AWS lambda
        run: npm install --omit=dev

      - name: Create Deploy Directory
        run: |
          mkdir -p nodejs/node_modules/farmhand
          cp -r ./node_modules/* nodejs/node_modules/
          cp -r ./src/* ./nodejs/node_modules/farmhand/
          cat package.json | jq '.main="index.js"' > ./nodejs/node_modules/farmhand/package.json

      - name: Create Zip
        run: zip -r nodejs.zip ./nodejs/

      - name: Deploy Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Zip
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nodejs.zip
          asset_name: nodejs.zip
          asset_content_type: application/zip

  release:

    name: Publish npm package
    needs: [ lambda ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org
          always-auth: true
          scope: '@tarosky'

      - name: Build Package
        run: bash bin/build.sh ${{ github.ref }}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN_TAROSKY }}
